### ISSUE TITLE
when i deployed to vercel i got adds on the website

### ISSUE THREAD

**Issue by aigamesmast** [thedogecraft/lunaar.org#10]
i stated getting random pop ups on the website when i deployed

**Comment by Logieboyyyyyyyyy** [comment]
this is part of the code so the developers can make money

**Comment by khaybarkhaybaryayahud** [comment]
> i stated getting random pop ups on the website when i deployed

fork the repo and remove the ads

**Comment by aigamesmast** [comment]
> > i stated getting random pop ups on the website when i deployed
> 
> fork the repo and remove the ads

how do i remove the ads

**Comment by khaybarkhaybaryayahud** [comment]
> > > i stated getting random pop ups on the website when i deployed
> > 
> > 
> > fork the repo and remove the ads
> 
> how do i remove the ads

# remove the code

**Comment by Nintendoboi22** [comment]
learn coding and look for the ads yourself
