### ISSUE TITLE
ads problem

### ISSUE THREAD

**Issue by hey122112** [thedogecraft/lunaar.org#21]
i just get the most nsfw ads on this proxy

**Comment by thedogecraft** [comment]
ok will fix.

**Comment by allmors** [comment]
> i just get the most nsfw ads on this proxy

Maybe you can try [hideipnetwork](https://github.com/Hideipnetwork/hideipnetwork-web)to deploy on [render](https://render.com)
![image](https://github.com/user-attachments/assets/d45e3f2e-8dc6-4b95-8aab-828ee854a1ff)

**Comment by hey122112** [comment]
> > i just get the most nsfw ads on this proxy
> 
> Maybe you can try [hideipnetwork](https://github.com/Hideipnetwork/hideipnetwork-web)to deploy on [render](https://render.com) ![image](https://github.com/user-attachments/assets/d45e3f2e-8dc6-4b95-8aab-828ee854a1ff)

i use a school chrombook

**Comment by hey122112** [comment]
> > i just get the most nsfw ads on this proxy
> 
> Maybe you can try [hideipnetwork](https://github.com/Hideipnetwork/hideipnetwork-web)to deploy on [render](https://render.com) ![image](https://github.com/user-attachments/assets/d45e3f2e-8dc6-4b95-8aab-828ee854a1ff)

idk how i would set this up on render because i don't use render at all
