### ISSUE TITLE
zip files always corrupted

### ISSUE THREAD

**Issue by issueacc** [thedogecraft/lunaar.org#23]
when i try to download zip files using lunaar, they always come out corrupted and dont work at all.

**Comment by thedogecraft** [comment]
Using the proxy?

**Comment by issueacc** [comment]
yes

**Comment by thedogecraft** [comment]
Using the proxy for downloading files is not the intended use, and I am not able to fix this.

**Comment by thedogecraft** [comment]
Please make an issue [here,](https://github.com/titaniumnetwork-dev/Ultraviolet) as this is what we use for a proxy.
