### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by LxFasT1** [thedogecraft/lunaar.org#26]
Everytime I try to load up lunaar.org,  it immediately redirects to a random website like whatever "tablepars.com" is or now "pulyantina.com" that can't load and I can't go back to lunaar.org. This all happens before I can do anything on the website so it is just broken for me. This has been going on for about a week or 2 and it might be succurly or my shitty chromebook sense I use it in school.
![Screenshot 2024-10-30 11 04 51 AM](https://github.com/user-attachments/assets/25162128-9b06-42ad-8784-6a508aab99e6)

**Comment by thedogecraft** [comment]
Looking in to this

**Comment by thedogecraft** [comment]
Issue found and fixed in the latest update was a problem with the ads issue should be fixed now.

**Comment by thedogecraft** [comment]
Just out of curiosity, what is the URL of the first tab

**Comment by LxFasT1** [comment]
bevindooker1.github.io/games1
He also has a main home page a just bevindooker1.github.io

**Comment by thedogecraft** [comment]
weird it's a old version of lunaar when it was called native

**Comment by iddu0** [comment]
bevindooker1.github.io don't click the go guardian killer
its a jumpscare
(I learned the hard way)

**Comment by LxFasT1** [comment]
I also learned that fun is funky too the hard way (it was kinda funny tho Ngl sense I had headphones on)
