### ISSUE TITLE
other problem with ads

### ISSUE THREAD

**Issue by hey122112** [thedogecraft/lunaar.org#27]
the problem is when i try to scroll down it redirects me to other website

**Comment by thedogecraft** [comment]
Issue found and fixed in the latest update

**Comment by iddu0** [comment]
> the problem is when i try to scroll down it redirects me to other website

Close the issue, it has been solved

**Comment by iddu0** [comment]
@Thedogecraft thanks

**Comment by hey122112** [comment]
> Issue found and fixed in the latest update

No it hasn't stop trying to hide it hadn't been fix okay

**Comment by iddu0** [comment]
maybe your doing something wrong? how is the issue caused

**Comment by hey122112** [comment]
> maybe your doing something wrong? how is the issue caused

maybe you should make it when i close out of the ads their not a shit ton more i understand you are trying to keep the website up because of the domain and everything but i feel their should be ads popping up every sec  and i am just trying to play some video games

**Comment by thedogecraft** [comment]
I didn't have control over this situation, so I switched to Google AdSense recently, and this issue should be resolved.

**Comment by iddu0** [comment]
> > maybe your doing something wrong? how is the issue caused
> 
> maybe you should make it when i close out of the ads their not a shit ton more i understand you are trying to keep the website up because of the domain and everything but i feel their should be ads popping up every sec and i am just trying to play some video games

i'm not even a developer of this project. i just saw the open issues and decided to comment. also, they need ads for money, to continue development.
