### ISSUE TITLE
about:blank error 

### ISSUE THREAD

**Issue by bahabryra** [thedogecraft/lunaar.org#30]
okay on other sites like monkeygg2.github.io running the about:blank bypasses the block if your fast enough (3 1/2 secs) but running it on lunnar just blocks it why???

**Comment by thedogecraft** [comment]
I'm am not sure. Can you provide a video?

**Comment by thedogecraft** [comment]
hello?

**Comment by bahabryra** [comment]
hi sorry im on winter break so i cant rn






On Tuesday, December 24, 2024 at 06:39:58 PM CST, Thedogecraft ***@***.***> wrote: 







hello?
