### ISSUE TITLE
about:blank loop

### ISSUE THREAD

**Issue by ghost** [thedogecraft/lunaar.org#9]
whenever site is open it consistently is making new about blank tabs

**Comment by ghost** [comment]
[Untitled_ Dec 11, 2023 11_28 AM.webm](https://github.com/Parcoil/nativegames.net/assets/117470728/803538b3-7baa-46de-904e-97112bd23015)

**Comment by SandwichOriginal** [comment]
Try resetting chrome web data and try again.
